contracts/urls.py
from django.urls import path
from . import views

app_name = "contracts"

urlpatterns = [
    # Получить данные о стоимости
    path('period-cost/', views.get_contracts_cost_in_period, name='period_cost'),
    path('project-costs/', views.project_costs, name='project_costs'),
]

employees/urls.py
from django.urls import path
from . import views
from .views import get_project_dates

app_name = 'employees'

urlpatterns = [
    path('employee/<int:pk>/', views.employee_detail, name='employee_detail'),
    # path('employee/<int:pk>/edit/', views.edit_employee, name='edit_employee'),
    path('employees/', views.employee_list, name='employee_list'),
    path('manager_list/', views.manager_list, name='manager_list'),
    path('add-project-employees/', views.add_project_employees, name='add_project_employees'),
    path('get-project-dates/', get_project_dates, name='get_project_dates'),
    path('bulk-create-assignments/', views.bulk_create_employee_assignments, name='bulk_create_assignments'),
    path('filter/', views.filtered_employee_list, name='filtered_list'),
]

equipment/urls.py
from django.urls import path
from . import views
app_name = 'equipment'

urlpatterns = [
    path('equipment/', views.equipment_list, name='equipment_list'),
    path('equipment/distribution/', views.equipment_distribution, name='equipment_distribution'),
    path('equipment/list-by-period/', views.equipment_list_by_period, name='equipment_list_by_period'),
    path('issue/', views.issue_equipment, name='issue_equipment'),
    path('issued/', views.equipment_issued_list, name='issued_list')
]

main_page/urls.py
from django.urls import path
from . import views

app_name = 'main_page'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('avtomatiz/', views.avtomatiz, name='avtomatiz'),
    path('contacts/', views.contacts, name='contacts'),
    path('reviews/', views.reviews, name='reviews'),
    path('search/', views.search, name='search'),
    path('search_choose/', views.search_choose, name='search_choose'),
]

project_organization/urls.py
from django.conf import settings
from django.contrib import admin
from django.templatetags.static import static
from django.urls import path, include
from django.views.static import serve
from employees.views import get_project_dates

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_page.urls', namespace='main_page')),
    path('', include('user.urls', namespace='user')),
    path('', include('user_profile.urls', namespace='user_profile')),
    path('', include('contracts.urls', namespace='contracts')),
    path('', include('departments.urls', namespace='departments')),
    path('', include('employees.urls', namespace='employees')),
    path('', include('equipment.urls', namespace='equipment')),
    path('', include('projects.urls', namespace='projects')),
    path('', include('subcontractors.urls', namespace='subcontractors')),
    path('', include('avtomatizations.urls', namespace='avtomatization')),
    path('', include('all_list_employees.urls', namespace='all_list_employees')),
    path('', include('constructors.urls', namespace='constractors')),
]

# Добавляем маршрут для медиафайлов (только в режиме разработки)
if settings.DEBUG:
    urlpatterns += [
        path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    ]


admin.site.site_header = 'Панель администратора'
admin.site.index_title = 'Зарегистрированные пользователи'

projects/urls.py
from django.urls import path
from . import views

app_name = 'projects'
urlpatterns = [
    path('project/<int:pk>/employees/', views.project_employees, name='project_employees'),
    path('project/<int:pk>/equipment/', views.project_equipment, name='project_equipment'),
    path('projects/', views.project_list, name='project_list'),
    path('project/<int:project_id>/export/', views.export_project_to_word, name='export_project'),
    # Список активных проектов
    path('active/', views.active_projects, name='active_projects'),
    # Список проектов по дате
    path('by-date/', views.projects_by_date, name='projects_by_date'),
    path('project/<int:project_id>/detail', views.search_project_detail, name='search_project_detail'),
    path('project-efficiency/', views.project_efficiency, name='project_efficiency'),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('user_register/', views.user_register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
]

main_page/models.py
from django.db import models

# Create your models here.

main_page/views.py
import requests
from django.contrib import messages
from django.urls import reverse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from contracts.models import Contract
from projects.models import Project


# Create your views here.

def index(request):
    return render(request, 'index.html')
def about(request):
    return render(request, 'about.html')
def avtomatiz(request):
    return render(request, 'avtomatiz.html')
def contacts(request):
    return render(request, 'contacts.html')
def reviews(request):
    return render(request, 'reviews.html')
def search_choose(request):
    return render(request, 'search_choose.html')
def search(request):
    query = request.GET.get('q', '').strip()
    search_type = request.GET.get('type', '')  # 'contract' или 'project'
    print(search_type, query)

    contracts = []
    projects = []

    if search_type == 'contract':
        # Ищем только по номеру договора
        contracts = Contract.objects.filter(number__icontains=query)

    elif search_type == 'project':
        # Ищем только по названию проекта
        projects = Project.objects.filter(title__icontains=query)

    else:
        # Если не указан тип — ищем и по договорам, и по проектам
        contracts = Contract.objects.filter(number__icontains=query)
        projects = Project.objects.filter(title__icontains=query)

    return render(request, 'search_results.html', {
        'query': query,
        'search_type': search_type,
        'contracts': contracts,
        'projects': projects,
    })

def search_by_contract_number(request):
    pass

main_page/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block title %}
О нас
{% endblock %}
{% block body %}
<main>
  <div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">Jumbotron example</span>
      </a>
    </header>

    <div class="p-5 mb-4 bg-body-tertiary rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">О компании</h1>
        <p class="col-md-8 fs-4"> Мы инжиниринговая и производственная компания.</p>
        <p class="col-md-8 fs-4"> Специализирумся на:</p>
        <ul>
          <li>на разработке и реализации комплексных решений по автоматизации;</li>
          <li>на производстве электрооборудования и аппаратуры автоматизации (в том числе взрывозащищенного) с использованием инновационных разработок;</li>
          <li>на выполнении научно-исследовательских и проектных работ в горно-химической промышленности.</li>
        </ul>
        <p class="col-md-8 fs-4"> Выполняем работы по:</p>
        <ul>
          <li>нразработке комплексного проекта технического перевооружения производства, включающего обоснованную спецификацию на поставку технологического оборудования;</li>
          <li>комплексному обследованию производства и разработке технического предложения, основанного на наиболее эффективных и экономичных решениях;</li>
          <li>поставке необходимого технологического оборудования, систем автоматического управления;</li>
        </ul>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-body-tertiary border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>

    <footer class="pt-3 mt-4 text-body-secondary border-top">
      © 2025
    </footer>
  </div>
</main>
{% endblock %}
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<div id="automa-palette"></div>

main_page/templates/avtomatiz.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Услуги
{% endblock %}
{% block body %}
<div class="container">
 <header class="border-bottom lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="link-secondary" href="#">Subscribe</a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-body-emphasis text-decoration-none" href="#">Проектная организация</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="#" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg>
        </a>
        <a class="btn btn-sm btn-outline-secondary" href="#">Sign up</a>
      </div>
    </div>
  </header>
  <div class="nav-scroller py-1 mb-3 border-bottom">
    <nav class="nav nav-underline justify-content-between">
      <a class="nav-item nav-link link-body-emphasis active" href="{% url 'main_page:index' %}">Главная</a>
      <a class="nav-item nav-link link-body-emphasis" href="{% url 'main_page:about' %}">О нас</a>
      <a class="nav-item nav-link link-body-emphasis" href="#">Услуги</a>
      <a class="nav-item nav-link link-body-emphasis" href="#">Проекты</a>
      <a class="nav-item nav-link link-body-emphasis" href="{% url 'main_page:contacts' %}">Контакты</a>
      <a class="nav-item nav-link link-body-emphasis" href="{% url 'main_page:reviews' %}" >Отзывы</a>
    </nav>
  </div>
    <main class="container">
    <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis">
    <div class="col-lg-6 px-0 avtomatiz">
      <h1 class="display-4 fst-italic">Автоматизация промышленных объектов</h1>
      <p class="lead my-3">При проектировании производственного объекта или принятии решения по автоматизации объекта, заказчик, чаще всего, имеет чёткое  представление про особенности технологического процесса и проблемы, связанные с «человеческим  фактором», которые планирует решить при помощи автоматизации. При этом, если заказчик не имеет достаточного опыта  автоматизации технологических процессов, он может склоняться к крайностям, которые сделают цену автоматизации неприемлемо высокой, или лишат автоматизацию эффективности, а именно:
«автоматизация без компромиссов» - заказчик пытается сделать свой объект полностью автоматическим, выдвигает завышенные требования к резервированию и надёжности автоматики, объёму информации и т.п. Требует устанавливать электронное и механическое оборудование самых известных мировых производителей. Такой подход вызывает чрезмерные затраты средств на автоматизацию, в связи с чем окупаемость такой автоматизации в разумные сроки становится сомнительной;
«затыкание дыр» - заказчик пытается решить установкой автоматики самые болезненные проблемы производства, при этом оставляя без внимания комплексные проблемы отсутствия автоматики. Такой подход приводит к низкой эффективности автоматизации, когда большое количество смежных систем, управляемых вручную, приводит к отсутствию ожидаемого эффекта от внедрения автоматики на критических производственных цепочках;
«много всего по низкой цене» - заказчик пытается использовать самые дешёвые средства автоматизации, чтоб получить полный контроль над технологическим процессом по  низкой цене. Чаще всего, низкая надёжность самого дешёвого оборудования приводит к тому, что систему автоматики больше ремонтируют, чем используют.

Имея опыт работы с электронным оборудованием различных производителей, наши специалисты в состоянии предложить оптимальные варианты контроллерного и другого оборудования, которые обеспечат необходимую надёжность и производительность системы по разумной цене.

Наша компания выполняет полный перечень монтажных и пусконаладочных работ. Контроль качества документации и производства, позволяет минимизировать сроки выполнения работ и свести к минимуму количество отказов оборудования во время эксплуатации системы автоматизации.

ООО «Институт горной электротехники и автоматизации» получил сертификат соответствия (СУ ОТ)  - система управления охраной труда, проектирования, производства машин и оборудования который соответствует СТБ 18001-2009.

К числу наиболее крупных проектов, реализованных для ОАО Беларуськалий» можно отнести:

модернизацию скиповой подъемной машины №1 ствола №4 рудника 1РУ-замена системы Г-Д на ТП-Д (разработка проектной и конструкторской документации, закупка и поставка оборудования, выполнение электромонтажных работ, выполнение пуско-наладочных работ);

ООО «Институт горной электротехники и автоматизации» в 2011 году  реализовало  первый в СНГ проект «Модернизация электропривода клетьевой подъемной установки рудника ЗРУ». Экономия электроэнергии при использовании частотного регулируемого электропривода составила 58%;

при модернизации электропривода ВГП рудника ЗРУ и рудника 1РУ впервые в качестве приводных электродвигателей были применены синхронные электродвигатели с постоянными магнитами и преобразователи частоты ROBICON. ООО «Институт горной электротехники и автоматизации» разработало микропроцессорную систему управления и программное обеспечение для проекта;

экономия электроэнергии при использовании нового электропривода составила 53%;

в 2011 году в содружестве с немецкой компанией Siemens AG ООО «Институт горной электротехники и автоматизации» разработало собственную высоковольтную ячейку с элегазовой изоляцией. В настоящее время в эксплуатации находится 703 ячейки;

ООО «Институт горной электротехники и автоматизации» провело модернизацию проходческих передвижных подъёмных установок для ОАО «Трест«Шахтоспецстрой». Эти установки используются при проходке стволов рудников. Электрооборудование машин было значительно изношено, морально устарело, влекло большие энергозатраты при проведении работ. ООО «Институт горной электротехники и автоматизации» выполнило следующие виды работ: полный демонтаж всего электрооборудования, изготовление, монтаж нового регулируемого электропривода с микропроцессорной системой управления, диагностика, ремонт и наладка механической части проходческих передвижных установок МПП-9 и МПП-17,5 которые успешно работают при проходке шахтных стволов на Петриковском ГОК;

ООО «Институт   горной  электротехники    и  автоматизации» изготовило оборудование для объекта: «Линии приготовления реагентов для ООО «ЕвроХим- Усольский калийный комбинат» (разработка конструкторской документации, изготовление оборудования с разработкой программного обеспечения);

ООО  «Институт   горной  электротехники    и  автоматизации» выполнило исследование сети 6-1 ЮкВ ОАО «Беларуськалий» для создания базы данных с выполнением расчетов токов короткого замыкания, разработало рекомендации по величине установок срабатывания релейной защиты сети, с обеспечением их селективной работы на основе специализированной компьютерной программы по расчету токов короткого замыкания в сети 6-10 кВ (с учетом их подпитки от работающих генераторов и синхронных электродвигателей);

ООО  «Институт   горной  электротехники    и  автоматизации» изготовил электрооборудование для объекта: Вакуум-кристаллизационная установка для кристаллизации калия хлористого на СОФ 4РУ ОАО «Беларуськалий»;

на строящемся Петриковском горно-обогатительном комбинате закончен монтаж и пуско-наладочные работы на двух шахтных подъемных клетьевых машинах 2Ц-6,5 х 2,8 ТД и ЦР-6хЗ,4/06-ТД поставляемых ООО «Институт горной электротехники и автоматизации»;

разработан алгоритм управления АСУТП по объекту «Оптимизация работоспособности процессов приготовления реагентов с последующей автоматизацией процессов приготовления реагентов на обогатительной фабрике Гремячинского ГОКа».

</p>

    </div>
  </div>
</main>>
    </div>
{% endblock %}

main_page/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Главная страница
{% endblock %}
{% block body %}
<div class="container">
  <header class="border-bottom lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="link-secondary" href="#">Subscribe</a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-body-emphasis text-decoration-none" href="#">Проектная организация</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        <a class="link-secondary" href="{% url 'main_page:search_choose' %}" aria-label="Search">
          <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"></circle><path d="M21 21l-5.2-5.2"></path></svg>
        </a>
        {% if request.user.is_authenticated %}
          <p class="me-2 mb-0">Вы вошли как: {{ request.user.username }}</p>
          <a href="{% url 'user:logout' %}" class="btn btn-danger mt-3">Выйти</a>
        {% else %}
          <a class="btn btn-sm btn-outline-secondary login_btn" href="{% url 'user:login' %}">Login</a>
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'user:register' %}">Sign up</a>
        {% endif %}
      </div>
    </div>
  </header>
  <div class="nav-scroller py-1 mb-3 border-bottom">
    <nav class="nav nav-underline justify-content-between">
      <a class="nav-item nav-link link-body-emphasis " href="{% url 'main_page:index' %}">Главная</a>
      <a class="nav-item nav-link link-body-emphasis" href="{% url 'main_page:about' %}">О нас</a>
      <a class="nav-item nav-link link-body-emphasis" href="#">Услуги</a>
      <a class="nav-item nav-link link-body-emphasis" href="{% url 'projects:project_list' %}">Проекты</a>
      <a class="nav-item nav-link link-body-emphasis" href="{% url 'main_page:contacts' %}">Контакты</a>
      <a class="nav-item nav-link link-body-emphasis" href="{% url 'main_page:reviews' %}" >Отзывы</a>
    </nav>
  </div>
</div>
<main class="container">
    <div class="p-4 p-md-5 mb-4 rounded text-body-emphasis bg-body-secondary">
    <div class="col-lg-6 px-0">
      <h1 class="display-4 fst-italic">Автоматизация промышленных объектов</h1>
      <p class="lead my-3">При проектировании производственного объекта или принятии решения по автоматизации объекта, заказчик, чаще всего, имеет чёткое  представление про особенности технологического процесса и проблемы, связанные с «человеческим  фактором», которые планирует решить при помощи автоматизации. При этом, если заказчик не имеет достаточного опыта  автоматизации технологических процессов, он может склоняться к крайностям, которые сделают цену автоматизации неприемлемо высокой, или лишат автоматизацию эффективности, а именно:.</p>
      <p class="lead mb-0"><a href="{% url 'main_page:avtomatiz' %}" class="text-body-emphasis fw-bold">Continue reading...</a></p>
    </div>
  </div>
<div class="dropdown">
  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
    Выберите интересующий вас отдел
  </a>
  <ul class="dropdown-menu dropdown-content" style="">
    {% for dept in departments %}
      <li><a class="dropdown-item" href="{% url 'departments:department_detail' dept.id %}">{{ dept.name }}</a></li>
    {% endfor %}
<!--    <h1 class="mt-4">Дополнительные ссылки:</h1>-->
        <ul class="list-group">
          <li class="list-group-item"><a href="{% url 'avtomatization:automation_department_detail' %}">Отдел проектирования систем автоматизации</a></li>
          <li class="list-group-item"><a href="{% url 'constractors:constract_department_detail' %}">Конструкторский отдел</a></li>
          <li class="list-group-item"><a href="{% url 'employees:employee_list' %}">Список сотрудников</a></li>
          <li class="list-group-item"><a href="{% url 'equipment:issued_list' %}">Посмотреть выданное оборудование</a></li>
<!--            <li class="list-group-item"><a href="{% url 'projects:project_list' %}">Список проектов</a></li>-->
<!--            <li class="list-group-item"><a href="{% url 'equipment:equipment_list' %}">Список оборудования</a></li>-->
<!--            <li class="list-group-item"><a href="{% url 'subcontractors:subcontractor_list' %}">Список субподрядных организаций</a></li>-->
<!--            <li class="list-group-item"><a href="{% url 'employees:employee_list' %}">Список сотрудников</a></li>-->
        </ul>
<!--      <li><a class="dropdown-item" href="#">Отдел проектирования электропривода</a></li>-->
<!--      <li><a class="dropdown-item" href="#">Отдел проектирования систем автоматизации</a></li>-->
<!--      <li><a class="dropdown-item" href="#">Конструкторский отдел</a></li>-->
<!--      <li><a class="dropdown-item" href="#">Отдел проектирования горных машин</a></li>-->
  </ul>
</div>
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

main_page/templates/search_choose.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Главная страница
{% endblock %}
{% block body %}
<div class="container">
  <header class="border-bottom lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="link-secondary" href="#">Subscribe</a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-body-emphasis text-decoration-none" href="#">Проектная организация</a>
      </div>
      <div class="col-4 d-flex justify-content-end align-items-center">
        {% if request.user.is_authenticated %}
          <p class="me-2 mb-0">Вы вошли как: {{ request.user.username }}</p>
          <a href="{% url 'user:logout' %}" class="btn btn-danger mt-3">Выйти</a>
        {% else %}
          <a class="btn btn-sm btn-outline-secondary login_btn" href="{% url 'user:login' %}">Login</a>
          <a class="btn btn-sm btn-outline-secondary" href="{% url 'user:register' %}">Sign up</a>
        {% endif %}
      </div>
    </div>
  </header>
  <form method="get" action="{% url 'main_page:search' %}">
    <div class="mb-3">
        <label for="q">Поиск:</label>
        <input type="text" name="q" id="q" class="form-control" placeholder="Введите запрос..." value="{{ query }}">
    </div>
    <div class="mb-3">
        <label>Тип поиска:</label><br>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="type" id="contract_search" value="contract"
                   {% if search_type == 'contract' %}checked{% endif %}>
            <label class="form-check-label" for="contract_search">Договор</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="type" id="project_search" value="project"
                   {% if search_type == 'project' %}checked{% endif %}>
            <label class="form-check-label" for="project_search">Проект</label>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Искать</button>
  </form>
    <div class="link_save">
        <a href="{%url 'contracts:period_cost'%}" class="btn btn-success">Получить данные о стоимости проектов</a>
    </div>
</div>
{% endblock %}

main_page/templates/search_results.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Результаты поиска договоров: "{{ query }}"
{% endblock %}
{% block body %}
<div class="container">
  <header class="border-bottom lh-1 py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <a class="link-secondary" href="#">Subscribe</a>
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-body-emphasis text-decoration-none" href="#">Проектная организация</a>
      </div>
    </div>
  </header>
    <div class="container">
        <h1>Результаты поиска</h1>
        <p>По запросу "<strong>{{ query }}</strong>" найдено:</p>
        {% if contracts %}
            <h3>Договоры</h3>
            <ul class="list-group">
                {% for contract in contracts %}
                    <li class="list-group-item">
                        <a href="{% url 'projects:project_employees' contract.id %}">
                            {{ contract.number }} -
                            {% with contract.projects.first as project %}
                                {% if project %}
                                    {{ project.title }}
                                {% else %}
                                    Без проекта
                                {% endif %}
                            {% endwith %}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% elif projects %}
            <h3>Проекты</h3>
            <ul class="list-group">
                {% for project in projects %}
                    <li class="list-group-item">
                    <a href="{% url 'projects:project_employees' project.id %}">
                            {{ project.title }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>Ничего не найдено.</p>
        {% endif %}
    </div>
</div>
{% endblock %}